### PR TITLE
adding ability to limit action list by package. fixes #105

### LINKED ISSUE #105: Missing action list <PACKAGE>
**Describe the bug**
We missed implementing the equivalent of `wsk action list PACKAGENAME`

### PR DESCRIPTION
**Pull request by justinedelson**
## Description

* Add the ability to limit the action list by package

## Related Issue

#105

## Motivation and Context

It's available in wsk, should be available in aio.

## How Has This Been Tested?

* Added unit test case
* Manual testing

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [X] I have signed the [Adobe Open Source CLA](http://opensource.adobe.com/cla.html).
- [X] My code follows the code style of this project.
- [X] My change requires a change to the documentation.
- [X] I have updated the documentation accordingly.
- [X] I have read the **CONTRIBUTING** document.
- [X] I have added tests to cover my changes.
- [X] All new and existing tests passed.

### CODE REVIEW

**Comment by justinedelson** [comment]
I should note that I debated using an arg vs. a flag here. Obviously `wsk` uses what OCLIF would consider an arg but I personally try to avoid optional args -- I think they make things confusing.

**Comment by shazron** [comment]
We've been trying to do a 1:1 with the wsk client (so we can be almost a drop-in replacement), so I think having it as an optional arg would be preferable. @purplecabbage ?

**Comment by purplecabbage** [comment]
I was thinking the same thing @shazron 
Do you know how to do optional args in oclif @justinedelson ?

**Comment by justinedelson** [comment]
@purplecabbage I do. I just don't like them :)

PR updated

**Pull request merged**
