### PR TITLE
Added log forwarding management commands

### PR DESCRIPTION
**Pull request by buskamuza**
## Description

Added `runtime:namespace:log-forwarding` commands for managing log forwarding settings for the namespace.

## Related Issue

- https://github.com/adobe/aio-cli-plugin-runtime/issues/247
- https://github.com/adobe/aio-lib-runtime/pull/70

## Motivation and Context

I/O Runtime is working on configurable Log Forwarding, which will allow a namespace to be configured to custom logs destination. Currently supported: Splunk, Azure Log Analytics. This PR allows logging configuration to be managed via aio CLI.

## How Has This Been Tested?

Auto tests are included.
Also, validated manually on existing I/O Runtime environment with my namespaces.

## Screenshots (if appropriate):

N/A

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] I have signed the [Adobe Open Source CLA](http://opensource.adobe.com/cla.html).
- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by meryllblanchet** [comment]
@Himavanth could you please review @buskamuza's PR ?

**Review by Himavanth — CHANGES_REQUESTED** [review]
@buskamuza I see the interactive approach with `aio rt namespace log-forwarding set` is a good addition to the non-interactive commands. 

- Currently `aio rt namespace log-forwarding --help` do not display the proper help with the relevant options (get and set). We can add index.js file under `log-forwarding` folder to get the proper help.
- The api does not work with `_` in place of namespace in the URL. We might need to handle this and throw an error before calling the API.

**Comment by buskamuza** [comment]
> Currently aio rt namespace log-forwarding --help do not display the proper help with the relevant options (get and set). We can add index.js file under log-forwarding folder to get the proper help.

Updated

**Comment by buskamuza** [comment]
> The api does not work with _ in place of namespace in the URL. We might need to handle this and throw an error before calling the API.

Need to confirm whether the API should support `_` and will update the CLI accordingly.

**Comment by buskamuza** [comment]
Agreed to prohibit usage of `_` namespace in CLI.

**Review by Himavanth — APPROVED** [review]

**Review by shazron — APPROVED** [review]

**Comment by rabbah** [comment]
Neat 👍

**Comment by Himavanth** [comment]
Thanks for this contribution @buskamuza . Merging.

**Pull request merged**
