### PR TITLE
WIP : support --docker aka blackbox actions

### PR DESCRIPTION
**Pull request by ddragosd**
> This is WIP. Please do not merge. 

Add support for [blackbox](https://github.com/apache/openwhisk/blob/master/docs/actions-docker.md) actions.

## Description

Added `--docker flag.

## Related Issue

N/A

## Motivation and Context

Allows special namespaces to deploy blackbox actions. This feature is not enabled by default for all namespaces. 

## How Has This Been Tested?

TBD

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] I have signed the [Adobe Open Source CLA](http://opensource.adobe.com/cla.html).
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by rabbah** [comment]
Hey @ddragosd - I have this implemented with tests if you want to take my patches or I'm happy to open a PR for it.

https://github.com/adobe/aio-cli-plugin-runtime/compare/master...rabbah:docker

**Comment by ddragosd** [comment]
@rabbah this is super helpful. let me know if you want to merge yours instead. Else I'm happy - and thankful - to cherrypick from yours.

**Comment by rabbah** [comment]
Here you go https://github.com/adobe/aio-cli-plugin-runtime/pull/125.

**Comment by ddragosd** [comment]
closing in favor of #125

**Pull request closed without merging**
